version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - postgresql  # Le service backend attend PostgreSQL
    networks:
      - app-network
    restart: unless-stopped

  postgresql:
    container_name: ms_pg_sql  # Nom du conteneur PostgreSQL
    image: postgres:15  # Utilisation de l'image officielle PostgreSQL version 15
    environment:
      - POSTGRES_USER=postgres  # Utilisateur PostgreSQL
      - POSTGRES_PASSWORD=postgres  # Mot de passe PostgreSQL
      - POSTGRES_DB=mydb  # Nom de la base de données à créer
    volumes:
      - pg_data:/var/lib/postgresql/data  # Volume pour persister les données PostgreSQL
    ports:
      - "5432:5432"  # Expose le port 5432 pour PostgreSQL
    networks:
      - app-network  # Réseau Docker pour la communication entre services
    restart: unless-stopped  # Le conteneur redémarre sauf s'il est arrêté manuellement

networks:
  app-network:
    driver: bridge
    external: true  # Le réseau existe déjà, pas besoin de le créer

volumes:
  pg_data:
    name: pg_data  # Spécifie explicitement le nom du volume, sans préfixe
    driver: local  # Volume persistant local pour les données PostgreSQL
