version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - backnodejsconvoiturage_pgdata:/var/lib/postgresql/data  # Volume monté ici
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
    external: true

volumes:
  backnodejsconvoiturage_pgdata:
    driver: local  # Cette ligne doit être correctement imbriquée sous "backnodejsconvoiturage_pgdata"
